tr_to_en = {
    "araba": "car",
    "uzay": "space",
    "robot": "robot",
    "gelecek": "future",
    "şehir": "city",
    "insan": "person",
    "gemi": "ship",
    "dünya": "earth",
    "modern": "modern",
    "ev": "house",
    "teknoloji": "technology",
    "uçak": "airplane",
    "bilim": "science",
    "sanat": "art",
    "yapay zeka": "artificial intelligence",
    "uzay gemisi": "spaceship",
    "geleceğin": "future",
    "cyberpunk": "cyberpunk",
    "atmosfer": "atmosphere",
    "futuristik": "futuristic",
    "neon": "neon",
    "ışık": "light",
    "yüksek teknoloji": "high technology",
    "koloni": "colony",
    "mars": "mars",
    "insansı": "humanoid",
    "portre": "portrait",
    "şehir manzarası": "cityscape",
    "uçan araba": "flying car",
    "hologram": "hologram",
    "enerji": "energy",
    "bilim kurgu": "science fiction",
    "gelecek şehir": "future city",
    "ileri teknoloji": "advanced technology",
    "konsept": "concept",
    "tasarım": "design",
    "detaylı": "detailed",
    "yüksek detay": "high detail",
    "sinematik": "cinematic",
    "uzaylı": "alien",
    "yapay": "artificial",
    "akıllı": "smart",
    "gökdelen": "skyscraper",
    "otonom": "autonomous",
    "drone": "drone",
    "bilgisayar": "computer",
    "telefon": "smartphone",
    "tablet": "tablet",
    "kadın": "woman",
    "erkek": "man",
    "çocuk": "child",
    "yaşlı": "elderly",
    "doğa": "nature",
    "orman": "forest",
    "dağ": "mountain",
    "deniz": "sea",
    "okyanus": "ocean",
    "nehir": "river",
    "göl": "lake",
    "plaj": "beach",
    "ada": "island",
    "çöl": "desert",
    "gök": "sky",
    "yıldız": "star",
    "gezegen": "planet",
    "galaksi": "galaxy",
    "astronot": "astronaut",
    "uydu": "satellite",
    "meteor": "meteor",
    "köprü": "bridge",
    "yol": "road",
    "ofis": "office",
    "havalimanı": "airport",
    "istasyon": "station",
    "park": "park",
    "gemi": "ship",
    "uçak": "aircraft",
    "helikopter": "helicopter",
    "tren": "train",
    "otobüs": "bus",
    "motorsiklet": "motorcycle",
    "bisiklet": "bicycle",
    "elektrikli araç": "electric vehicle",
    "portre": "portrait",
    "yüz": "face",
    "heykel": "sculpture",
    "resim": "painting",
    "grafiti": "graffiti",
    "poster": "poster",
    "illüstrasyon": "illustration",
    "doktor": "doctor",
    "mühendis": "engineer",
    "öğretmen": "teacher",
    "bilim insanı": "scientist",
    "sanatçı": "artist",
    "programcı": "programmer",
    "lazer": "laser",
    "kristal": "crystal",
    "metal": "metallic",
    "cam": "glass",
    "karanlık": "dark",
    "renkli": "colorful",
    "parlak": "bright",
    "minimalist": "minimalistic"
}

def enhance_prompt(prompt):
    # ... mevcut fonksiyon ...